
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./personal_info.ipynb

class MyDict(dict):
    def gets(self, names):
        names = names.split(',')
        names = map(lambda s:s.strip(), names)
        return map(lambda s:self[s], names)
        return names


import smtplib
import json

with open("../personal_info.json", 'r') as f:
    info = json.load(f)
    info = MyDict(info)

def sendEmail(message):
    sender, password, smtp, recipient = info.gets("sender, password, smtp, recipient ")

    smtp = MyDict(smtp)
    address, port = smtp.gets("address, port ")

    with smtplib.SMTP_SSL(address, port ) as server :
        server.login(sender, password)
        server.sendmail(sender, recipient, message)