
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./main.ipynb

import nbexp_anilist
import nbexp_bilibili
from functools import partial
print = partial(print, flush=True)

from time import sleep, mktime
from datetime import datetime
import sys
def now():return mktime(datetime.now().timetuple())
def now_s():
    s = datetime.now().isoformat()
    return s[:s.index('.')]
now_s()

def timer(slient_mode = False):
    pf = print
    def empty_func(*args):
        pass
    pf = empty_func if slient_mode else print

    def split_by_time(*args):
        pf("-"*60 , now_s(), *args)

    split_by_time()
    t1 = now()
    yield t1, 0

    while True:
        t2 = now()
        split_by_time("time costs %2d secs"%(t2 - t1))
        yield t2, t2 - t1

from IPython.display import display, Javascript
def save_notebook(): display(Javascript('IPython.notebook.save_checkpoint();'))

import traceback

def run_user_code(mod):
    try:
        name=mod.__name__
        main = getattr(mod, 'main')
        main()
    except Exception:
        print("Exception in user code: %s"%name)
        traceback.print_exc(file=sys.stdout)



run_user_code(nbexp_anilist)
run_user_code(nbexp_bilibili)

