
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./main.ipynb

import nbexp_anilist
import nbexp_bilibili

import traceback
def run_user_code(fn):
    try:
        fn()
        return True
    except Exception:
        print("Exception in user code:"%fn.__module__)
        print("-"*60)
        traceback.print_exc() #file=sys.stdout)
        print("-"*60)
        return False

from time import sleep, mktime
from datetime import datetime
import sys
def now():return mktime(datetime.now().timetuple())
def now_s():
    s = datetime.now().isoformat()
    return s[:s.index('.')]
now_s()

hrs = 1
sec = hrs * 60 * 60
while True:
    t1 = now()
    print(now_s(), end=' ')

    run_user_code(nbexp_anilist.main)
    run_user_code(nbexp_bilibili.main)

    t2 = now()
    print("duration %3d seconds"%(t2 - t1))
    if __doc__ == 'Automatically created module for IPython interactive environment':
        break;

    sleep(sec)